services:
  redis:
    image: redis:7-alpine
    container_name: rate-redis
    ports:
      - "6379:6379"
    networks:
      - rate-net

  limiter:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.limiter   # relative path
    container_name: rate-limiter
    environment:
      - PORT=8080
      - REDIS_ADDR=redis:6379
      - ALGORITHM=sliding
      - CAPACITY=10
      - REFILL_RATE=1.0
      - WINDOW_SEC=60
      - ENABLE_HIERARCHICAL=true
      - GLOBAL_CAPACITY=1000000
      - GLOBAL_REFILL_RATE=10000.0
      - TENANT_CAPACITY=100000
      - TENANT_REFILL_RATE=1000.0
      - USER_CAPACITY=100
      - USER_REFILL_RATE=1.0
      - ENDPOINT_CAPACITY=10
      - ENDPOINT_REFILL_RATE=0.5
    ports:
      - "8080:8080"
    networks:
      - rate-net
    depends_on:
      - redis

  demo:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.demo
    container_name: demo-backend
    environment:
      - PORT=8081
    ports:
      - "8081:8081"
    networks:
      - rate-net

  sidecar:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.sidecar
    container_name: rate-sidecar
    environment:
      - PORT=9090
      - UPSTREAM_URL=http://demo:8081
      - RATE_LIMITER_URL=http://limiter:8080
      - RATE_LIMIT=10
      - USE_HIERARCHICAL=false
      - FAIL_OPEN=false
    ports:
      - "9090:9090"
    networks:
      - rate-net
    depends_on:
      - limiter
      - demo

networks:
  rate-net:
    driver: bridge