FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o demo-backend ./cmd/demo-backend

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/demo-backend .
EXPOSE 8081
CMD ["./demo-backend"]