FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o rate-limiter ./cmd/limiter

FROM alpine:latest
RUN apk add --no-cache ca-certificates wget
WORKDIR /root/
COPY --from=builder /app/rate-limiter .
EXPOSE 8080 8082
CMD ["./rate-limiter"]