FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o gateway-sim ./cmd/gateway-sim

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/gateway-sim .
EXPOSE 8081
CMD ["./gateway-sim"]
