FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o sidecar ./cmd/sidecar

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/sidecar .
EXPOSE 9090
CMD ["./sidecar"]